# Generated by Django 4.2.4 on 2023-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_customuser_image_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Categorie_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Categorie_name', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
