# Generated by Django 4.2.4 on 2023-09-10 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=300, null=True)),
                ('author_name', models.CharField(max_length=300, null=True)),
                ('published_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.categories')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transtiondetails',
            fields=[
                ('tran_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trans_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.books')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
