# Generated by Django 4.2.4 on 2023-09-10 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_books_transtiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='customuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
