# Generated by Django 4.2.4 on 2023-09-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_books_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transtiondetails',
            old_name='trans_date',
            new_name='taken_date',
        ),
    ]
