# Generated by Django 4.2.4 on 2023-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_transtiondetails_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtiondetails',
            name='tran_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
